services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_Python
    command: sh -c "cd python && python main.py"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:16-bullseye"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 2
    ports:
      - "5432:5432"

  front:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_React
    restart: "always"
    ports:
      - "5173:5173"

  nginx:
    image: "nginx:stable-alpine3.17-slim"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app


volumes:
  db_data: