services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_Python
    command: sh -c "cd python/src && 
                    python3 manage.py migrate && 
                    python3 manage.py collectstatic --noinput &&
                    python3 manage.py syncdb &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} -w 20 --timeout 120"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/python/src/static/
    restart: "always"

  db:
    image: "postgres:16-alpine3.18"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "always"

  front:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_React
    restart: "always"

  nginx:
    image: "nginx:stable-alpine3.17-slim"
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/python/src/static/
    restart: "always"

volumes:
  db_data:
  static_volume: