services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_Python
    command: sh -c "python3 python/src/manage.py migrate && 
                    python3 python/src/manage.py collectstatic --noinput &&
                    python3 python/src/manage.py runserver 0.0.0.0:${PORT}"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/python/src/static/


  db:
    image: "postgres:16-bullseye"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  front:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_React
    restart: "always"

  nginx:
    image: "nginx:stable-alpine3.17-slim"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/python/src/static/

volumes:
  db_data:
  static_volume: