# Generated by Django 5.0.6 on 2024-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_idea_options_alter_ideatag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='image_url',
        ),
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.CharField(default='', max_length=1000, verbose_name='Картинка'),
        ),
    ]
