# Generated by Django 5.0.6 on 2024-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_idea_image_url_idea_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gigachat_prompt",
                    models.CharField(
                        default="Напиши конкретную идею опираясь на цели устойчивового развития ООН (1 предложение) по развитию города Сысерть, опираясь на следующие факты: Мне нравится: {like}. Я хочу: {want}. Я умею: {can}",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
    ]
