# Generated by Django 5.0.6 on 2024-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
