# Generated by Django 5.0.6 on 2024-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_idea_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="Можете вписать любое слово - оно будет нормализовано автоматически",
                        max_length=64,
                        unique=True,
                        verbose_name="Нормальная форма матерного слова",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матерное слово",
                "verbose_name_plural": "Матерные слова",
            },
        ),
    ]
