# Generated by Django 5.0.6 on 2024-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_successdetector_testitem_successdetectortestitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testitem',
            options={'verbose_name': 'Шаг детектора успеха', 'verbose_name_plural': 'Шаги детектора успеха'},
        ),
        migrations.RenameField(
            model_name='testitem',
            old_name='after_text',
            new_name='after_test',
        ),
        migrations.AlterField(
            model_name='testitem',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Это тест?'),
        ),
    ]
