# Generated by Django 5.0.6 on 2024-06-01 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_testitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="cookie",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testitem",
            name="after_test",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Текст после теста",
            ),
        ),
        migrations.AlterField(
            model_name="testitem",
            name="answer1",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Правильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="testitem",
            name="answer2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Неправильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="testitem",
            name="answer3",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Неправильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="testitem",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Описание"),
        ),
    ]
