# Generated by Django 5.0.6 on 2024-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_adminuser_cookie_alter_testitem_after_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="photo_url",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Ссылка на аватарку",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="cookie",
            field=models.JSONField(
                blank=True, default="{}", null=True, verbose_name="Сохранение прогресса"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
