# Generated by Django 5.0.6 on 2024-06-01 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_adminuser_photo_url_alter_adminuser_cookie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.CreateModel(
            name="IdeaLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.idea",
                        verbose_name="Идея",
                    ),
                ),
                (
                    "like",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайк",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк идее",
                "verbose_name_plural": "Лайки идей",
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="likes",
            field=models.ManyToManyField(
                related_name="likes",
                through="app.IdeaLike",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
