# Generated by Django 5.0.6 on 2024-06-01 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_idea_created_by_alter_adminuser_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idealike",
            old_name="like",
            new_name="user",
        ),
    ]
