# Generated by Django 5.0.6 on 2024-06-01 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_rename_like_idealike_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idealike",
            name="idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.idea",
                unique=True,
                verbose_name="Идея",
            ),
        ),
        migrations.AlterField(
            model_name="idealike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="Лайк",
            ),
        ),
    ]
