# Generated by Django 5.0.6 on 2024-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_idealike_idea_alter_idealike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='history',
            field=models.BooleanField(default=True, verbose_name='История (речка)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='idea_generate',
            field=models.BooleanField(default=True, verbose_name='Генератор идей'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='idea_view',
            field=models.BooleanField(default=True, verbose_name='Биржа идей'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='success_detector',
            field=models.BooleanField(default=True, verbose_name='Детектор успеха'),
        ),
    ]
