# Generated by Django 5.0.6 on 2024-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_siteconfiguration_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('date', models.CharField(max_length=500, verbose_name='Дата')),
                ('image_url', models.CharField(max_length=500, verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Блок истории',
                'verbose_name_plural': 'Блоки истории',
            },
        ),
    ]
