# Generated by Django 5.0.6 on 2024-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ideatag',
            constraint=models.UniqueConstraint(fields=('idea', 'tag'), name='unique_idea_tag'),
        ),
    ]
