# Generated by Django 5.0.6 on 2024-06-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_ideatag_unique_idea_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealike',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.idea', verbose_name='Идея'),
        ),
        migrations.AlterField(
            model_name='idealike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AddConstraint(
            model_name='idealike',
            constraint=models.UniqueConstraint(fields=('idea', 'user'), name='unique_idea_user'),
        ),
    ]
