# Generated by Django 5.0.6 on 2024-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_idealike_idea_alter_idealike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Картинка'),
        ),
    ]
