FROM python:3.12.2-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ../python/requirements.txt ./

RUN apt update && \
    apt install libpq-dev gcc -y &&  \
    pip install -r /app/requirements.txt

COPY .. .
